### PR TITLE
feat(int-staged): Support lint-staged 10

### PR DESCRIPTION
**Pull request by sapegin**
BREAKING CHANGE:

* Your configs will be upgraded to lint-staged 10.
* eslintExtensions, prettierExtensions and stylelintExtensions options are removed
* lintStagedRules option has a new format, see the docs for more details

### CODE REVIEW

**Review by okonet — APPROVED** [review]
LGTM although I must confess I don’t understand all of it. Maybe add code comments to explain a bit better?

**Comment by sapegin** [comment]
Sure, I'll add some comments ;-)

The general idea is to infer extensions from npm scripts.  For example, if you have `lint` script that runs ESLint for `js` and `ts` files, this task will add lint-staged rule that runs ESLint for the same extensions. And will overwrite it if you change it manually. But it won't remove your completely custom rules (unless they happened to run ESLint too ;-)

**Comment by sapegin** [comment]
I think it's good now. I've fixed a few things and added comments.

**Review by okonet — APPROVED** [review]
Much better now!

**Pull request merged**
